export default {
  $id: "https://sampleshop.com/product.json",
  type: "object",
  properties: {
    name: { type: "string" },
    qty: { type: "integer" },
    price: { type: "number" },
    image: { type: "string" },
    description: { type: "string" },
    section: { type: "string" },
    sizechart: { type: "string" },
    displayname: { type: "string" },
    images: { type: "string" },
    size: { type: "string" },
    order: { type: "integer" },
  },
  required: [
    "name",
    "qty",
    "price",
    "image",
    "description",
    "section",
    "sizechart",
    "displayname",
    "images",
    "size",
    "order",
  ],
};
