name: client

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install test dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run check
